<template>
	<view class="cu-modal" :class="showModalName== modalName ?'show':''" :style="'margin-top:'+CustomBar+ 'px'">
		<view class="cu-dialog">
			<view class="cu-bar bg-white justify-end">
				<view class="content">监理复杂程度调整</view>
				<view class="action" @tap="hideModal">
					<text class="cuIcon-close text-red"></text>
				</view>
			</view>
			<view class="padding-xl">
				<uni-collapse animation="outer" accordion="true" @change="change">
					<uni-collapse-item v-for="(item,index) in dataList" :key="index" :title="item">
						<view style="display: flex;flex-wrap: wrap;" v-if="checkOpen >= 1">
							<view v-for="(i,j) in data[isactive].list" :key="j">
								<view class="p-2 bnb ml-2"
									style="white-space: normal;"
									:class="clickIndex == j ? 'active' : ''"
									@click="addClass(j)"
								>{{i.category}}</view>
							</view>
							<view class="dlf-group lt">
								<view class="w-100 dlf-li font lt border-b"
											v-for="(m, k) in data[isactive].list[clickIndex].chilren"
											:key="k" 
											@tap="assignment"
											:data-val="m.xs"
											:data-key="k"
											>
									<view  style=" white-space: pre-wrap;display: flex;">
										<view class="iconBLue mr-1" style="font-size: 30rpx;">{{m.xs}}</view>
										<view>{{m.value}}</view>
									</view>
								</view>
							</view>
						</view>
					</uni-collapse-item>
				</uni-collapse>
			</view>
		</view>
	</view>
</template>

<script>
	import {modalMixin} from "@/common/base/modalMixin"
	
	export default {
		mixins: [modalMixin],
		props: {
			showModalName: {
				type: String,
				default: null
			}, // 弹框可见标志
		},
		data() {
			return {
				isactive: 0 ,
				clickIndex: 0,
				modalName:'sjfGuo_blb',
				CustomBar:this.CustomBar,
				data:[
					{
						list:[
							{
								category:'有色金属、黄金、铀矿、其他矿种采选工程 化工矿新技术采选工程、黑色冶金露天采矿工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category: '黑色冶金坑内采矿工程 煤炭矿山采选、水煤浆制备与燃烧应用、煤层气抽放工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'35'
									},
									{
										value:'施工图设计(%)',
										xs:'65'
									},
								]
							},
							{
								category: '化学矿常规技术采选工程 非金属矿采选工程、黑色冶金选矿工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'70'
									},
								]
							}
						]
					},
					{
						list:[
							{
								category:'加工冶炼工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'35'
									},
									{
										value:'施工图设计(%)',
										xs:'65'
									},
								]
							},
							{
								category: '核加工工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
						]
					},
					{
						list:[
							{
								category:'一般石油、石化、化工工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'35'
									},
									{
										value:'施工图设计(%)',
										xs:'65'
									},
									{
										value:'基础设计(%)',
										xs:'50'
									},
									{
										value:'详细设计(%)',
										xs:'50'
									},
								]
							},
							{
								category: '新技术石油、石化、化工工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'50'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
									{
										value:'基础设计(%)',
										xs:'60'
									},
									{
										value:'详细设计(%)',
										xs:'40'
									},
								]
							},
							{
								category:'火化工、核化工、化纤、医药工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
									{
										value:'基础设计(%)',
										xs:'50'
									},
									{
										value:'详细设计(%)',
										xs:'50'
									},
								]
							},
							{
								category: '核设施退役工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'60'
									},
									{
										value:'施工图设计(%)',
										xs:'40'
									},
									{
										value:'基础设计(%)',
										xs:'65'
									},
									{
										value:'详细设计(%)',
										xs:'35'
									},
								],
								
							},
						]
					},
					{
						list:[
							{
								category:'核能、送电、变电工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category: '火电工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'70'
									},
								]
							},
							{
								category: '水库、水电、潮汐工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'25'
									},
									{
										value:'招标设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category:'风电工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category: '引调水工程(建筑筑物)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'25'
									},
									{
										value:'招标设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category: '引调水工程(渠道管线)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'招标设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'35'
									},
								]
							},
							{
								category:'河道治理工程(建筑筑物)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'25'
									},
									{
										value:'招标设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category: '河道治理工程(河道堤防)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'55'
									},
									{
										value:'招标设计(%)',
										xs:'10'
									},
									{
										value:'施工图设计(%)',
										xs:'35'
									},
								]
							},
							{
								category: '灌区田间工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'60'
									},
									{
										value:'施工图设计(%)',
										xs:'40'
									},
								]
							},
							{
								category: '水土保持工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'70'
									},
									{
										value:'招标设计(%)',
										xs:'10'
									},
									{
										value:'施工图设计(%)',
										xs:'20'
									},
								]
							}
						]
					},
					{
						list:[
							{
								category:'铁路工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category:'水运、索道工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'城市交通工程(城市道路)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category:'城市交通工程(地铁/轻轨)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category:'民用机场工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'45'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
						]
					},
					{
						list:[
							{
								category:'建筑与室外工程(I级)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'10'
									},
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'建筑与室外工程(II级)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'15'
									},
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'55'
									},
								]
							},
							{
								category:'建筑与室外工程(III级)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'20'
									},
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'住宅小区(组团)工程',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'25'
									},
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'45'
									},
								]
							},
							{
								category:'住宅工程',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'25'
									},
									{
										value:'施工图设计(%)',
										xs:'75'
									},
								]
							},
							{
								category:'古建筑保护性建筑工程',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'30'
									},
									{
										value:'初步设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'智能建筑弱电系统工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'室内装修工程',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'50'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'园林绿化(I、II级)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'70'
									},
								]
							},
							{
								category:'园林绿化(III级)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'30'
									},
									{
										value:'初步设计(%)',
										xs:'20'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'人防工程',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'10'
									},
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'市政公用工程(I、II级)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'市政公用工程(III级)',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'50'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'广播电视、邮政工程工艺部分',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'电信工程',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'60'
									},
									{
										value:'施工图设计(%)',
										xs:'40'
									},
								]
							},
							{
								category:'建筑工程专业(建筑)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'33~43'
									},
									{
										value:'初步设计(%)',
										xs:'33~43'
									},
									{
										value:'施工图设计(%)',
										xs:'33~43'
									},
								]
							},
							{
								category:'建筑工程专业(结构)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'24~30'
									},
									{
										value:'初步设计(%)',
										xs:'24~30'
									},
									{
										value:'施工图设计(%)',
										xs:'24~30'
									},
								]
							},
							{
								category:'建筑工程专业(设备)',
								chilren:[
									{
										value:'方案设计(%)',
										xs:'28~38'
									},
									{
										value:'初步设计(%)',
										xs:'28~38'
									},
									{
										value:'施工图设计(%)',
										xs:'28~38'
									},
								]
							},
						]
					},
					{
						list:[
							{
								category:'农业（综合开发、畜牧养殖、水产养殖、设施农业工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'40'
									},
									{
										value:'施工图设计(%)',
										xs:'60'
									},
								]
							},
							{
								category:'农业（生态工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'100'
									},
								]
							},
							{
								category:'林业（林木种子园、森林防火、病虫害防治工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'80'
									},
									{
										value:'施工图设计(%)',
										xs:'20'
									},
								]
							},
							{
								category:'林业（造林、营林工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'70'
									},
									{
										value:'施工图设计(%)',
										xs:'30'
									},
								]
							},
							{
								category:'林业（标准化苗圃、花卉基地、植物园、自然保护区、森林公园、生态观光园、林业局(场)总体设计、野生动物园、濒危野生动植物保护工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'60'
									},
									{
										value:'施工图设计(%)',
										xs:'40'
									},
								]
							},
							{
								category:'林业（综合开发与科技园区工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'50'
									},
									{
										value:'施工图设计(%)',
										xs:'50'
									},
								]
							},
							{
								category:'林业（木材运输、贮木场工程）',
								chilren:[
									{
										value:'初步设计(%)',
										xs:'30'
									},
									{
										value:'施工图设计(%)',
										xs:'70'
									},
								]
							},
							
						]
					}
				],
				dataList:['2.矿山采选工程','3.加工冶炼工程','4.石油化工工程','5.水利电力工程','6.交通运输工程','7.建筑市政工程','8.农业林业工程'],
				check:[]
			}
		},

		methods:{
			addClass(index){
				this.clickIndex = index
			},
			change(e){
				this.check = e
				this.isactive = e[0]
				this.clickIndex = 0 
			}
		},
		computed:{
			checkOpen(){
				return this.check.length
			}
		}
	}
</script>

<style scoped>
	.bnb {
		border: 2rpx solid #00a0e0;
		border-bottom: none;
	}
	.active {
		background: #3788e4;
		color: #fff;
	}
</style>